### ISSUE TITLE
No access

### ISSUE THREAD

**Issue by naturekid72** [tenable/pi_sniffer#1]
Hi,

when I flash the SD and startup the PI0W no AccessPoint appears or do I have to access it another way? 

And can I use this -> https://www.waveshare.com/1.3inch-oled-hat.htm instead of the Adafruit OLED Bonnet? What in the config would I have to change?

**Comment by jacob-baines** [comment]
Hey @naturekid72, I just updated the README explaining how to use the controls. Let me know if that helps.

Currently, the code is tied to the Adafruit OLED Bonnet.
