### ISSUE TITLE
Pi Sniffer case

### ISSUE THREAD

**Issue by talmage** [tenable/pi_sniffer#7]
Are you aware of any cases for the Pi Sniffer, either ready-made or printable?  Please post links to them in the README.

**Comment by chopper-2656** [comment]
i found this case which worked great with the PI Zero and the Adafruit 128x64 OLED Bonnet.

https://www.amazon.ca/GeeekPi-Raspberry-Starter-Heatsink-Screwdriver/dp/B08MVH2JJ1/ref=sr_1_4?dchild=1&keywords=pi+zero+w+case&qid=1617114019&s=electronics&sr=1-4

**Comment by talmage** [comment]
That's a nice case.  I'm looking for one that encloses both the Pi Zero and the bonnet.

**Comment by talmage** [comment]
I bought a case from Daddy Makes Stuff and Things on Tindie.com: https://www.tindie.com/products/daddy-makes-stuff-and-things/case-unus/.  I'm happy with it.
